### PR TITLE
Adds single quote rule to eslint

### PR DESCRIPTION
**Pull request by sirugh**
Added single quote rule to eslint.

`console.log("Hello, world!") => console.log('Hello, world!')`

I also ordered the rules alphabetically. I didn't reorder anything else as I wasn't sure if `extends` array is ordered.

### CODE REVIEW

**Comment by jimbo** [comment]
Why do we need this? Unless there was a change necessitating this, quotes should be handled by Prettier, not ESLint.

**Comment by sirugh** [comment]
> Why do we need this? 

Conflicting rules. ESLint applies "double" by default. We specify single in prettier. We can do this or we can turn it off.

**Comment by jimbo** [comment]
> Conflicting rules. ESLint applies "double" by default. We specify single in prettier. We can do this or we can turn it off.

Is this a result of merging in the `eslint:recommended` preset? If so, did you want to add the preset that disables rules that prettier handles?

**Comment by sirugh** [comment]
Oh looks like we already have it: https://github.com/magento-research/magento-eslint/blob/master/index.js#L8

Closing!

**Pull request closed without merging**
